version: '3.8'
services:
  viewer_service_proxy:
    depends_on:
      - viewer_service

    image: "traefik:2.2"
    container_name: "viewer_service_proxy"

    environment:
      TZ: "Australia/Melbourne"

    command:
      - "--providers.file.filename=/etc/traefik/traefik.yml"

    volumes:
      - type: bind
        source: "./viewer_service/traefik.yml"
        target: "/etc/traefik/traefik.yml"

    ports:
      - "8080:80"

    networks:
      - inventory

  viewer_service:
    depends_on:
      - item_inventory
      - item_catalogue

    build: "./viewer_service"
    image: "viewer_service:latest"
    container_name: "viewer_service"

    environment:
      DJANGO_SECRET_KEY: "ChangeMe123"
      DJANGO_DEBUG: "True"
      ITEM_INVENTORY_URI: "postgres://graphql:password@item_inventory:5432/inventory"
      ITEM_CATALOGUE_URI: "http://item_catalogue:8080"

    command: ["-b", "0.0.0.0", "-p", "8080", "viewer_service.asgi:application"]

    networks:
      - inventory

  item_inventory:
    image: "postgres:12.4"
    container_name: "item_inventory"

    environment:
      POSTGRES_USER: "graphql"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "inventory"

    networks:
      - inventory

  item_inventory_management:
    depends_on:
      - item_inventory

    image: "flyway/flyway:latest"
    container_name: "item_inventory_management"

    command:
      - "-url=jdbc:postgresql://item_inventory/inventory"
      - "-user=graphql"
      - "-password=password"
      - "-connectRetries=30"
      - "migrate"

    volumes:
      - type: bind
        source: "./item_inventory_service/sql/"
        target: "/flyway/sql"

    networks:
      - inventory

  item_catalogue:
    build: "./item_catalogue_service"
    image: "item_catalogue_service:latest"
    container_name: "item_catalogue"

    entrypoint: ["python3"]
    command: ["service.py", "--host", "0.0.0.0", "--port", "8080"]

    networks:
      - inventory

networks:
  inventory:
