---
global:
  sendAnonymousUsage: false

entryPoints:
  web:
    address: ":80"

http:
  routers:
    backend:
      entryPoints:
        - "web"
      service: backend

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://viewer_service:8080/"
